CREATE TABLE public."HierarchyDetails" (
  "HierarchyDetailId"     UUID         PRIMARY KEY,
  "OrgCode"               VARCHAR(50)  NOT NULL,
  "OrgName"               VARCHAR(255) NOT NULL,
  "City"                  VARCHAR(255) NULL,
  "State"                 VARCHAR(255) NULL,
  "Address1"              VARCHAR(255) NULL,
  "Address2"              VARCHAR(255) NULL,
  "Zip"                   VARCHAR(50)  NULL,
  "Phone"                 VARCHAR(50)  NULL,
  "Phone2"                VARCHAR(50)  NULL,
  "Email"                 VARCHAR(255) NULL,
  "Fax"                   VARCHAR(50)  NULL,
  "EffectiveDate"         TIMESTAMPTZ  NULL,
  "EndDate"               TIMESTAMPTZ  NULL,
  "ContactFirstName"      VARCHAR(100) NULL,
  "ContactSecondName"     VARCHAR(100) NULL,
  "ContactPhoneNumber"    VARCHAR(50)  NULL,
  "AltContactFirstName"   VARCHAR(100) NULL,
  "AltContactSecondName"  VARCHAR(100) NULL,
  "AltContactPhoneNumber" VARCHAR(50)  NULL,
  "Logo"                  TEXT         NULL,
  "DisplayColor"          VARCHAR(50)  NULL,
  "TextColor"             VARCHAR(50)  NULL,
  "TotalConfigLevels"     INTEGER      NULL,
  "ConfigLevelColor"      VARCHAR(50)  NULL,
  "IsActive"              BOOLEAN      NOT NULL DEFAULT TRUE,
  "CreatedBy"             UUID         NULL,
  "CreatedOn"             TIMESTAMPTZ  NULL DEFAULT NOW(),
  "LastUpdatedBy"         UUID         NULL,
  "LastUpdatedOn"         TIMESTAMPTZ  NULL,
  "HierarchyId"           UUID         NULL,
  "ClassificationId"      UUID         NULL,
  CONSTRAINT "FK_HierarchyDetails_Hierarchy"
    FOREIGN KEY ("HierarchyId") REFERENCES public."Hierarchy" ("HierarchyId")
);
